# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # DATABASES
    # --------------------------------------------------------------------------------

    # PostgreSQL
    pgdb:
      image: postgres:${POSTGRES_VERSION}
      restart: always
      working_dir: /application
      ports: 
        - "${POSTGRES_PORT}:5432"
      networks:
        - labnet
      volumes:
        - pg_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}      

    # pgAdmin4
    pgadmin:
      image: dpage/pgadmin4:${PGADMIN_VERSION}
      restart: always
      networks:
        - labnet      
      volumes:
        - pgadmin:/var/lib/pgadmin
        - "${PGADMIN_SERVER_JSON_FILE}:/pgadmin4/servers.json"
      depends_on:
        - pgdb
      environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "${PGADMIN_PUBLIC_PORT}:80"        

# ======================================================================================================================
# VOLUMES
# ======================================================================================================================

volumes:       
  pg_data:
  pgadmin:
