# ======================================================================================================================
# INCLUDES (require Docker Compose 2.20+)
# ======================================================================================================================

include:
  # PostgreSQL configuration
  - path: ./docker.conf/compose-postgres.yml
    project_directory: .                      # to load servers.json properly 
    env_file: ./docker.conf/postgres.env

  # Maria configuration (uncomment to use MariaDB)
  # - path: ./docker.conf/compose-maria.yml
  #   project_directory: ..
  #   env_file: ./docker.conf/maria.env

# ======================================================================================================================
# NETWORKS
# ======================================================================================================================

networks:
  labnet:
    driver: bridge
    name: labnet

# ======================================================================================================================
# SERVICES
# ======================================================================================================================

services:

    # --------------------------------------------------------------------------------
    # WEB SERVER
    # --------------------------------------------------------------------------------

    webserver:
      image: nginx:alpine
      working_dir: /application
      restart: always
      networks:
        - labnet
      volumes:
          - ./app:/application
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
       - "${NGINX_HTTP_PORT}:80"

    php-fpm:
      image: phpdockerio/symfony-hi:${PHP_VERSION}
      build: phpdocker/php-fpm
      working_dir: /application
      networks:
        - labnet
      volumes:
        - ./app:/application
        - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/${PHP_VERSION}/fpm/conf.d/99-overrides.ini'
